version: "3"
services:
  express:
    build: .
    image: tourapi:1
    container_name: tourapi
    ports:
      - 3020:3020
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

