version: "3"
services:
  nginx:
    build: .
    image: nginx:0
    ports:
      - "80:80"
    volumes:
      - ${EXTERNAL_REACT_PATH}:/build
      - ./conf.d:/etc/nginx/conf.d
    extra_hosts:
      - "host.docker.internal:host-gateway"
