version: "3"
services:
  mysqldb:
    image: mysql:8
    container_name: tourdb
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumns:
      - ~/mysql:/var/lib/mysql